query GetAllPosts(
    $where: PostWhereInput!
    $orderBy: [PostOrderByWithRelationInput!]
) {
    posts(where: $where, orderBy: $orderBy) {
        id
        title
        content
        isDraft
        cover_picture
        slug
        created_at
        commentCount {
            count
        }
        author {
            id
            first_name
            nickname
            last_name
            email
            avatar
        }
        userId
        Category {
            id
            name
        }
        categoryId
        Tags {
            id
            name
        }
    }
}
