query getAllPostComments(
    $where: CommentWhereInput
    $orderBy: [CommentOrderByWithRelationInput!]
) {
    comments(where: $where, orderBy: $orderBy) {
        id
        content
        created_at
        picture
        author {
            id
            nickname
            avatar
        }
    }
}
