query GetPostData($where: PostWhereUniqueInput!) {
    post(where: $where) {
        id
        slug
        title
        content
        cover_picture
        Category {
            id
            name
        }
        isDraft
        User_likes {
            id
        }
        author {
            nickname
            id
            first_name
            last_name
            image
            email
            avatar
        }
        Tags {
            id
            name
        }
    }
}
