query GetPostData($where: PostWhereUniqueInput!) {
    post(where: $where) {
        id
        slug
        title
        content
        cover_picture
        isDraft
        author {
            id
            first_name
            last_name
            email
            avatar
        }
        Tags {
            id
            name
        }
    }
}
